### ISSUE TITLE
Modificação de formato

### ISSUE THREAD

**Issue by DonRyuDragoni** [HeitorG/Perl-Brasil#1]
Consideraria reescrever a apostila utilizando [markdown](https://daringfireball.net/projects/markdown/), [LaTeX](https://www.latex-project.org/) ou alguma outra forma que facilitasse a modificação dela, também ajudando os que desejam colaborar com o projeto?

Sem contar que, utilizando markdown, não seria complicado converter para outros formatos (inclusive e-books) utilizando [pandoc](http://pandoc.org/), caso alguém se interesse.

**Comment by l4mbd0x** [comment]
Concordo. 

Obs: Estou aqui pois queria avisar e ver se dava de contribuir com a apostila. O Aviso é referente a pág 16 da apostila, onde é dito que o programa imprimiria 'Boa noite' e na real o que é impresso, não sei se intencionalmente... 'Bom dia'. Se foi intencional, na página 17 depois da primeira imagem, será divertido colocar um 'Troll né' onde está escrito 'Simples né'. Ou simplesmente trocar a mensagem do programinha. Gostei muito da iniciativa.

**Comment by DonRyuDragoni** [comment]
Estou fazendo manualmente a conversão para markdown nesse momento, e, caso o @HeitorG aceite a proposta, abro assim que possível um pull request. :smile: 

Também vim procurar como contribuir, pois encontrei vários erros de português que me incomodaram. Antes de corrigi-los, contudo, gostaria de facilitar as contribuições, até mesmo para ajudar a fazer a minha. :stuck_out_tongue_winking_eye:

**Comment by htrgouvea** [comment]
Olá, fico feliz que vocês estão afim de contribuir com este projeto, e no mesmo momento fico triste, pois não estou tendo tempo para continua-lo, qualquer contribuição irá ser muito bem vinda, sempre que eu estiver tempo vou olhar os Pull Request e aprova-los se necessario.
