### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by DonRyuDragoni** [HeitorG/Perl-Brasil#3]
Pensei em algo que poderia tornar essa apostila mais acessível e, ao mesmo tempo, mais fácil de receber contribuições: por que não criar uma organização e transformar as apostilas em uma [página do github](https://help.github.com/articles/user-organization-and-project-pages/)? Assim, quem quisesse ler as apostilas, poderia simplesmente ir ao site e seguir os links; quem quisesse tê-las offline, poderia simplesmente baixar os arquivos das apostilas e convertê-los.

A minha ideia é criar uma estrutura de diretórios da seguinte forma:

```
|_ ...
|_ apostilas
    |_ Apostila Básica
        |_ 01.md
        |_ 02.md
        |_ 03.md
        |_ 04.md
        |_ ...
    |_ Apostila Intermediária
        |_ 01.md
        |_ 02.md
        |_ ...
    |_ ...
```

Onde o primeiro nível indicaria o nome da apostila e, dentro dessa, os capítulos dela, escritos em markdown (porque é uma linguagem de marcação muito simples de usar e/ou converter para um html a ser renderizado na página das apostilas ou para pdf/epub/mobi para ser lido offline). Assim, a página olharia esse diretório e renderizaria os links e as apostilas, e qualquer modificação nessa estrutura se propagaria para a página acessada, sem que os usuários ou contribuidores tenham de lidar com html/javascript/etc.

Tenho um shell script bem simples pra gerar um epub e/ou mobi usando o [pandoc](http://pandoc.org/) e o [kindlegen](http://www.amazon.com/gp/feature.html?docId=1000765211) que posso disponibilizar. Não saberia, contudo, como converter os arquivos em markdown para html pois nunca usei javascript ou fiz qualquer coisa focada em web. Tenho, contudo, interesse nisso e poderia comprometer-me a usar um pouco de meu tempo livre a gerar essa funcionalidade.

**Comment by htrgouvea** [comment]
Acho a ideia super válida, provavelmente assim que sobrar um tempo eu já começo a desenvolver a mesma. Obrigado pela sugestão!
Assim que eu começar coloco o novo link para a ORG aqui para você acompanhar também.
